// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octoporty.Agent.Data;

#nullable disable

namespace Octoporty.Agent.Migrations
{
    [DbContext(typeof(OctoportyDbContext))]
    [Migration("20260130133642_AddSettings")]
    partial class AddSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Octoporty.Shared.Entities.ConnectionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisconnectReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisconnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortMappingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedAt");

                    b.HasIndex("PortMappingId");

                    b.ToTable("ConnectionLogs");
                });

            modelBuilder.Entity("Octoporty.Shared.Entities.PortMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowSelfSignedCerts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("InternalPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InternalUseTls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalDomain")
                        .IsUnique();

                    b.ToTable("PortMappings");
                });

            modelBuilder.Entity("Octoporty.Shared.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConnectionLogId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PortMappingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResponseSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionLogId");

                    b.HasIndex("PortMappingId");

                    b.HasIndex("Timestamp");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Octoporty.Shared.Entities.Settings", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Octoporty.Shared.Entities.ConnectionLog", b =>
                {
                    b.HasOne("Octoporty.Shared.Entities.PortMapping", "PortMapping")
                        .WithMany()
                        .HasForeignKey("PortMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PortMapping");
                });

            modelBuilder.Entity("Octoporty.Shared.Entities.RequestLog", b =>
                {
                    b.HasOne("Octoporty.Shared.Entities.ConnectionLog", "ConnectionLog")
                        .WithMany()
                        .HasForeignKey("ConnectionLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Octoporty.Shared.Entities.PortMapping", "PortMapping")
                        .WithMany()
                        .HasForeignKey("PortMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConnectionLog");

                    b.Navigation("PortMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
